### PR TITLE
Feature/profile query

### PR DESCRIPTION
**Pull request by memsharded**
Hi Mathieu,

This PR:
- handles the refactor of create_profile for reuse among tests
- add tests for your functionality
- Handles the refactor of profiles, to be able to load profiles for any location.

Cheers!

### CODE REVIEW

**Comment by mropert** [comment]
That looks OK but just a little note: the "Dev=true" option is now displayed in the [scopes] of the profile, even if it's not defined in the file.
I know that it's because it's added by default by wouldn't that be strange for users, seeing an option they didn't set?

**Comment by memsharded** [comment]
Yes, I was thinking of it when I was implemented the tests, and thought the same. Then I thought the thing is that if we hide it, it will also hide when users explicitly define it, and that will be also confusing. Do you think then it would be better to hide the "dev" scope in the output? Please tell me to fix. @lasote feedback welcome too.

In any case, I think it could be better to move this forward (with our without the dev scope) tomorrow, so it gets into the 0.17 release (Tuesday), otherwise, it will have to wait until next release.

**Comment by lasote** [comment]
I prefer to show the `Dev=true`.

**Comment by memsharded** [comment]
This PR was already merged, I think it can be closed now. Thanks!

**Pull request closed without merging**
